version: 2

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - migrations
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable:
      - shadow
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  funlen:
    lines: 100
    statements: 50
  
  lll:
    line-length: 140
  
  misspell:
    locale: US
  
  gocritic:
    enabled-checks:
      - appendAssign
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentFormatting
      - defaultCaseOrder
      - dupImport
      - emptyStringTest
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - nilValReturn
      - rangeValCopy
      - regexpMust
      - sloppyLen
      - stringXbytes
      - typeAssertChain
      - underef
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - dupl
    - gocritic
    - gocyclo
    - funlen
    - gosec
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - funlen
        - gocyclo
        - dupl
    
    - path: load_testing/
      linters:
        - errcheck
        - funlen
        - gosec
    
    - path: tests/
      linters:
        - errcheck
        - funlen
        - gosec
    
    - text: "Error return value of.*logger.*is not checked"
      linters:
        - errcheck
    
    - text: "G404.*weak random"
      linters:
        - gosec
    
    - text: "result 0.*is always nil"
      linters:
        - unparam

  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
